---
kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ .Values.labels }}
  labels:
    app: {{ .Values.labels }}

spec:
  replicas: {{ .Values.REPLICAS_COUNT }}
  selector:
    matchLabels:
      app: {{ .Values.labels }}
  template:
    metadata:
      labels:
        app: {{ .Values.labels }}
    spec:
      containers:
        - name: {{ .Values.labels }}
          image: containous/whoami
          ports:
            - name: web
              containerPort: 80
          env:
          - name: WHOAMI_NAME
            value: {{ .Values.WHOAMI_NAME }}
          resources:
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: web
            initialDelaySeconds: 5
            periodSeconds: 5
