---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.labels }}-ingress
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: internal
  rules:
  - host: "{{ .Values.hostname }}.{{ .Values.tld }}"
    http:
      paths:
      ## Path ⌄⌄⌄⌄⌄⌄⌄
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.labels }}
            port:
              number: 80